nodeLinker: pnp

packageExtensions:
  "@storybook/react-vite@*":
    dependencies:
      typescript: "*"
  "storybook@*":
    dependencies:
      "@storybook/addon-a11y": "*"
      "@storybook/addon-docs": "*"
      "@storybook/react-vite": "*"
      "@testing-library/dom": "*"
      react: "*"
      react-dom: "*"
      vite: "*"
